### ISSUE TITLE
Poggit

### ISSUE THREAD

**Issue by GamerDaniel3000** [thebigsmileXD/BedWars#1]
Please publish a build on poggit

**Comment by thebigsmileXD** [comment]
Poggit is buggy again. It does not compile apibossbar, so gameapi fails to compile, so bedwars fails to compile. Blame @Sofe
Btw @sofe: i tried to redeliver the builds for everything - apibossbar will not compile under any circumstances.

**Comment by SOF3** [comment]
No idea, but it is working for me.
https://poggit.pmmp.io/ci/SOF3/BedWars
Check your webhook delivery logs?

**Comment by SOF3** [comment]
https://poggit.pmmp.io/ci/SOF3/apibossbar/~
It works for me.

**Comment by SOF3** [comment]
```
Jun/verbose.4.log:Jun 4 22:33:18.483 [ed17-4e1d5e2220119f3a-AMS] 140.82.115.69: POST webhooks.gh.repo/bcf40a98f078112a
Jun/verbose.4.log:Jun 4 22:33:19.290 [ed17-4e1d5e2220119f3a-AMS] Safely completed: 807ms
Jun/info.4.log:Jun 4 22:33:18.487 [ed17-4e1d5e2220119f3a-AMS] Handling push event from GitHub API for repo thebigsmileXD/apibossbar
```
Poggit indeed receives the push event.

**Comment by GamerDaniel3000** [comment]
I need this plugin :3rd_place_medal:

**Comment by GamerDaniel3000** [comment]
Please fix the problem with poggit and bedwars @thebigsmileXD @SOF3

**Comment by thebigsmileXD** [comment]
Chill and give us time. Spam may result in block

**Comment by thebigsmileXD** [comment]
Building still failed. Probably found the source of the issue. Debugging asap

**Comment by thebigsmileXD** [comment]
Build completed
