### ISSUE TITLE
Can't build?

### ISSUE THREAD

**Issue by ShushImSam** [thebigsmileXD/BedWars#10]
Its pretty simple.. I go in Build Mode but is it only void.. How am I supposed to build in that? I tried to use a WorldEdit plugin  but when i was setting a block it was dissapearing when an update was made next to it..

**Comment by thebigsmileXD** [comment]
Blame the world editor that you are using, seems outdated. BlockSniper and MagicWE2 are definitely working and not creating those bugs. I am wondering if i could create a little platform by default to avoid the need of a world editor plugin.
Plans surely are to build a custom map that will be shipped with the plugin for free
