### ISSUE TITLE
Respawn Points are not corret

### ISSUE THREAD

**Issue by note3crafter** [thebigsmileXD/BedWars#12]
When you are in a round and you die you are not put back to the spawn point but to the world spawn point and who you mine the beds comes nix

**Comment by thebigsmileXD** [comment]
Investigating this issue

**Comment by thebigsmileXD** [comment]
Do you have playerdata saving enabled? Imo it is best to have a seperate minigame server, and turn save-player-data off. This makes players also spawning in the hub

**Comment by thebigsmileXD** [comment]
Closing as missing response
