### ISSUE TITLE
Hit player with enchanted item: Call to a member function inTeam() on null

### ISSUE THREAD

**Issue by mote166** [thebigsmileXD/BedWars#21]
When a player hits another player with any enchanted item, this internal error message shows:
```
Call to a member function inTeam() on null" (EXCEPTION) in "plugins/BedWars_dev-7.phar/src/xenialdan/BedWars/libs/xenialdan/gameapi/event/DefaultSettingsListener" at line 292
```

**Comment by mote166** [comment]
also the winner doesn't get the win message cuz it was sent on the default world when he was still getting teleported to it . change it to make it broadcast the message for everyone

**Comment by thebigsmileXD** [comment]
> also the winner doesn't get the win message cuz it was sent on the default world when he was still getting teleported to it . change it to make it broadcast the message for everyone

This is intentionally done, since i did not want every world to be "spammed" with messages.

**Comment by mote166** [comment]
the only spam is when a player joins the game, no need to make it send "the game needs players" each time a player joins it cuz then thats a spam, players are xlever enough to know from just 1 message and if they want to play they will leave everything and go play

**Comment by mote166** [comment]
@thebigsmileXD what happened to this issue?

**Comment by mote166** [comment]
should i just give up on this plugin ?

**Comment by thebigsmileXD** [comment]
> when a player hits a player with any enchanted item ( knowckback stick , swords ) the player gets the internal error message

Can not confirm

**Comment by thebigsmileXD** [comment]
Can not reproduce
