### ISSUE TITLE
+Error

### ISSUE THREAD

**Issue by TheWalkingDrift** [thebigsmileXD/BedWars#23]
![bedwars](https://user-images.githubusercontent.com/51052379/63620971-11ed4d00-c5f3-11e9-8e66-714dd2670fcf.PNG)

**Comment by TheWalkingDrift** [comment]
This error will be shown in console when I start the Server

**Comment by TheWalkingDrift** [comment]
Can you speak german ?

**Comment by thebigsmileXD** [comment]
Ja :-) kannst du bitte einen crashlog hochladen? Sind in /crashdumps, das würde mir segr helfen danke :)

**Comment by TheWalkingDrift** [comment]
Habe den Fehler gefunden habe vergessen deine Gameapi zu installieren

**Comment by TheWalkingDrift** [comment]
Dein Plugin ist übrigens Super!
