### ISSUE TITLE
No "Info" command

### ISSUE THREAD

**Issue by KadTheHunter** [thebigsmileXD/BedWars#24]
When you run `/bw info` nothing happens, and on console this error shows:
`[01:44:03] [Server thread/CRITICAL]: InvalidArgumentException: "Unknown argument supplied: info" (EXCEPTION) in "plugins/BedWars.phar/src/xenialdan/BedWars/commands/BedwarsCommand" at line 121`

**Comment by thebigsmileXD** [comment]
The info command is not yet fully implemented

**Comment by thebigsmileXD** [comment]
Implemented in 2.0.0
