### ISSUE TITLE
/bw leave dont work with perms

### ISSUE THREAD

**Issue by towuk118** [thebigsmileXD/BedWars#25]
Hello friend, you have a small mistake, put here "true"
![image](https://user-images.githubusercontent.com/28830162/64179521-fb08ef00-ce6b-11e9-95ff-c6da5e6d0bbd.png)
, because even the players with " permission: bedwars.command.leave" I can leave the game and use: /bw info /bw leave and please I love it I ability to add a sign with the inscription: 
======
[Bed Wars]
NAME_GAME
LEAVE
=======
to leave the game click on the sign

**Comment by thebigsmileXD** [comment]
Huh? 

> players with " permission: bedwars.command.leave" I can leave the game 

This is correct and intentional?
