### ISSUE TITLE
Break and blace blocks

### ISSUE THREAD

**Issue by Takabrycheri34** [thebigsmileXD/BedWars#26]
Why can't players place or destroy blocks?

**Comment by thebigsmileXD** [comment]
have you checked the breakable blocks config?

**Comment by Takabrycheri34** [comment]
It occurred to me to check later ... I did not have time to close the issue and avoid the beautiful figure ... Sorry for the inconvenience and my superhuman intelligence
(and sorry for my bad english)

**Comment by thebigsmileXD** [comment]
No problem 😅
