### ISSUE TITLE
Issues I found with your plugin

### ISSUE THREAD

**Issue by waumiller1818** [thebigsmileXD/BedWars#27]
When makeing a new world its emptey tryed useing a custom map still blank unless you delete the files in one you delete it and name the one you want the name with new world you named

Shops dont stay
Status command dont work
When spawning users dont spawn on there 
Resources dont spawn like its suppose to

Am runing latest par off pogit

**Comment by thebigsmileXD** [comment]
Sorry, i don't understand you
