### ISSUE TITLE
Player dies twice, lands in lobby

### ISSUE THREAD

**Issue by thebigsmileXD** [thebigsmileXD/BedWars#30]
See #21 
> "When a player dies twice they go back to the lobby and not bedwars spawn"

**Comment by vasilishunter** [comment]
That happened to me right when I downloaded the plugin then it self-fixed itself and now it’s happening again

**Comment by vasilishunter** [comment]
Can you tell me why this happens?

**Comment by thebigsmileXD** [comment]
No idea yet. But i can confirm

**Comment by thebigsmileXD** [comment]
I am currently busy writing another plugin, this is why this repo is currently stale. I will try to update asap

**Comment by vasilishunter** [comment]
Thanks a lot for putting your time and effort without being payed seriously I don’t understand why you do it but I am glad and you are appreciated

**Comment by vasilishunter** [comment]
For me it was due to another plugin

**Comment by thebigsmileXD** [comment]
^ above issue is solved. Also, can not reproduce on 2.0.0
