### ISSUE TITLE
Beds don’t sync up

### ISSUE THREAD

**Issue by ange0770** [thebigsmileXD/BedWars#32]
Hi so how do I have the beds work? They don’t work

**Comment by thebigsmileXD** [comment]
Have you enabled them in the setup? Remember, the teams must exist

**Comment by KostyaJRZ** [comment]
i need to set "noBed" to false?

**Comment by thebigsmileXD** [comment]
> i need to set "noBed" to false?

That would only allow sleep.

> Hi so how do I have the beds work? They don’t work

For beds to function the corresponding team color must exist
