### ISSUE TITLE
a join command to work with slappers

### ISSUE THREAD

**Issue by jasin** [thebigsmileXD/BedWars#34]
As the title says, can we get a join command so that this will work with slappers?

I was thinking something like this, I'm completely new to this so I have no idea if this code actually works. Unless there is a way to do the same thing with slappers editing the Joinevent, but I don't know how to do that. Please advise
```
case "join":
                {
                        if (!$sender->hasPermission("bedwars.command.join")) {
                                $sender->sendMessage(TextFormat::RED . "You do not have permission to run this command");
                                return true;
                        }
                        if (is_null($arena = Loader::getInstance()->getArenas()args[1]??null)) {
                                $sender->sendMessage(TextFormat::RED . "Arena not found" . args[1]);
                                return;
                        }
                        if (!$arena->joinTeam($sender)) {
                                $sender->sendMessage(TextFormat::RED . "Error joining");
                    }
```

**Comment by thebigsmileXD** [comment]
Indeed a good idea
Code is a little incorrect, but that's fine

**Comment by jasin** [comment]
I was trying to use poggit to build the phar so I could submit a patch, but I can't get poggit to build the fork of this repo so I can test as it needs virions to run. But thank you for considering this.

**Comment by thebigsmileXD** [comment]
You can run it with downloaded virion files if running from source, install DEVirion and the necessary virions from the poggit.yml

**Comment by thebigsmileXD** [comment]
#14 Might be related

**Comment by jasin** [comment]
I've added a PR, if you have any suggestions please share

**Comment by thebigsmileXD** [comment]
Since the PR is merged and the command seems to work, i am going to close this
