### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by 2cool4u567** [thebigsmileXD/BedWars#36]
this isnt your plugin

**Comment by thebigsmileXD** [comment]
Ah, ok 🙃
So you think it is notecrafters plugin or what? ;:D
https://github.com/thebigsmileXD/BedWars/network/members
![grafik](https://user-images.githubusercontent.com/8733998/66311630-2ff6de80-e90f-11e9-8580-f0ed79a35bc2.png)

**Comment by note3crafter** [comment]
this is not my Plugin this is XenialDan`s Plugin @2cool4u567 I have a Outdatet version

**Comment by thebigsmileXD** [comment]
@note3crafter i might create a pull request to update your version to a newer version, but i planned to add translations very soon anyways :P 

It would be good and kind if you can help with the translation files though

German: Wär echt super und nett wenn ihr mir mit den Deutschen Übersetzungen helfen könntet sobald das plugin dafür halbwegs bereit ist ^^

**Comment by note3crafter** [comment]
Ja das wurde es @thebigsmileXD hast mich ja leider auf Telegramm blockiert oder so könnte dirauf der deutschen version gerne helfen ^^ muss jedoch schauen wann ich zeit dafür finde habe grade selbst "codingstress" xd
