### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by laith98** [thebigsmileXD/BedWars#49]
IN MCPE 1.14 

Shop Not Working (Need Update Codes )

or open shop from command to use in slapper when villager not working*

and When choosing a world it should be FolderName Not LevelName

Please Fix The Plugin to last version

and Thank You.

**Comment by thebigsmileXD** [comment]
Have you got the Update Codes? Where can i use them, are them like SHiFT Codes?

Thanks for giving so many informations. Read #47 and do issues properly

**Comment by laith98** [comment]
i am updating codes and i am make plugin shop

**Comment by laith98** [comment]
Do you need help in update the plugin?
