### ISSUE TITLE
Feature Request - Arena defined by Region

### ISSUE THREAD

**Issue by Starflux** [thebigsmileXD/BedWars#50]
I am using Pocketmine hosted on plug pocketmine.

I am limited to one world currently.

I am able to define regions with specific flags however when using BedWars the config is applied to the whole world. The plugin itself works as described.

I suppose I am asking for a region parameter be built into the setup to allow defining a BedWars Arena within a world. This would allow me to continue regioning off area specific to minigames.

Many thanks
Star

**Comment by thebigsmileXD** [comment]
Hi. Sorry, but this feature can not be implemented. Arenas are world based in gameapi, and it would probably take me years to implement that
