### ISSUE TITLE
how do you setup a bed? idk how because they respawn.

### ISSUE THREAD

**Issue by gamerthegamer61** [thebigsmileXD/BedWars#51]

**Comment by gamerthegamer61** [comment]
and when the game ends it closes the server

**Comment by thebigsmileXD** [comment]
use `/bw setup`, click "edit world" and place beds. They are automatically detected.
You set team spawnpoints in the same menu (click "edit spawn points") and place the corresponding blocks

**Comment by thebigsmileXD** [comment]
> and when the game ends it closes the server

Open another issue and report the output of console
