### ISSUE TITLE
Shop not opening

### ISSUE THREAD

**Issue by xXKHaLeD098Xx** [thebigsmileXD/BedWars#55]
So this is my first time using this plugin, i installed all the extra virions for it work and all
i did setup everything in the arena but when i tried to play i couldn't open the shop whatsoever.

**Comment by thebigsmileXD** [comment]
Why don't you simply use the prebuilt .phar from poggit? ;)
It could be that your InvMenu version does not match the one used in the release of this plugin. If running from source, use the virion versions in https://poggit.pmmp.io/ci/thebigsmileXD/BedWars/BedWars/dev:17
Download them at the "babs" links
![image](https://user-images.githubusercontent.com/8733998/79392724-27ddc280-7f74-11ea-94a9-aa1be5683f76.png)

---
Please validate that you are not having any entity protection or entity AI plugins on your server.
Consider running a seperated server for games that utilize https://github.com/thebigsmileXD/gameapi. See https://github.com/thebigsmileXD/gameapi/issues/9 for FAQ
