### ISSUE TITLE
Plugib

### ISSUE THREAD

**Issue by qaqapro** [thebigsmileXD/BedWars#56]
Best plugin. But There is no bed setup

**Comment by thebigsmileXD** [comment]
Bed setup = In map build mode, place beds. Break a bed to register the bed. Duplicate of #8

**Comment by qaqapro** [comment]
Dude i did it what you say but not working you can add this on  setup ui.
Plz help

21 Nis 2020 Sal 04:15 tarihinde XenialDan <notifications@github.com> şunu
yazdı:
