### ISSUE TITLE
internal server error when i join.

### ISSUE THREAD

**Issue by concavepizza12** [thebigsmileXD/BedWars#65]
i get a internal server error when i use join sign
console output:
[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\NetworkBinaryStream::putString() must be of the type string, int given, called in phar://C:/Users/dylan/Desktop/ShotBlaster/bedwars/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddActorPacket.php on line 211" (EXCEPTION) in "src/pocketmine/network/mcpe/NetworkBinaryStream" at line 62

**Comment by thebigsmileXD** [comment]
Make sure to update the plugin. apibossbar had an update, so did gameapi, so did this plugin if i remember correctly. If not, i will schedule a build later
